variables: secrets.yml

web_server: yes

templates:
  global:
    notify:
      task:
        title: 'New Download'
        template: html
        via:
          - email:
              from: '{? email.user ?}'
              to: '{? email.user ?}'
              smtp_host: '{? email.smtp ?}'
              smtp_port: '{? email.port ?}'
              smtp_username: '{? email.user ?}'
              smtp_password: '{? email.pass ?}'
              smtp_tls: yes
              html: yes
  tv:

    private_torrents: no

    series:
      settings:
        tv:
          exact: yes
          propers: 3 days
          set:
            path: '{? location.shows ?}'
      tv:
        - TVSHOW1
        - TVSHOW2
        - TVSHOW3
        - TVSHOW4
    transmission:
      enabled: yes
      host: '{? transmission.host ?}'
      port: '{? transmission.port ?}'
      username: '{? transmission.user ?}'
      password: '{? transmission.pass ?}'

tasks:
  showrss.karmorra.info-tv:
    priority: 7
    rss: '{? transmission.rss ?}'
    digest: daily email
    template: tv
schedules:
  # Run every task once an hour
  - tasks: showrss.karmorra.info-tv
    interval:
      hours: 3
